# https://taskfile.dev

version: '3'

tasks:

  test:
    cmds:
      - go test ./...
    silent: true

  build-executable:
    deps:
      - test
    cmds:
      - go build
    silent: true

  build-docker-image:
    deps:
      - test
    cmds:
      - docker build -t chord-renderer:latest .
    silent: true
