# https://taskfile.dev

version: '3'

tasks:

  test:
    cmds:
      - go test ./...
    silent: true

  build-executable:
    deps:
      - test
    cmds:
      - go build
    silent: true

  build-docker-image:
    deps:
      - test
    cmds:
      - docker build -t tinosteinort/chord-renderer:latest .
    silent: true

  push-docker-image:
    deps:
      - build-docker-image
    cmds:
      - docker push tinosteinort/chord-renderer:latest
    silent: true

  build-readme:
    cmds:
      - ./README.md.sh
    silent: true

  build:
    deps:
      - build-executable
      - build-docker-image
      - build-readme
